/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ffffff",
        "on-secondary-container": "#00311f",
        "secondary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#004397",
        "surface-container": "#1c1f27",
        "tertiary-fixed": "#ffddb8",
        "surface-container-low": "#181b23",
        "tertiary-container": "#a66900",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-container": "#ffffff",
        "on-error": "#690005",
        "on-surface-variant": "#c1c6d7",
        "inverse-surface": "#e0e2ed",
        "background": "#10131b",
        "secondary-fixed-dim": "#4edea3",
        "outline": "#8b90a0",
        "on-background": "#e0e2ed",
        "on-tertiary-fixed-variant": "#653e00",
        "error-container": "#93000a",
        "surface-tint": "#aec6ff",
        "secondary": "#4edea3",
        "on-primary": "#002e6b",
        "surface-container-highest": "#32353d",
        "surface": "#10131b",
        "primary-fixed-dim": "#aec6ff",
        "error": "#ffb4ab",
        "primary-fixed": "#d8e2ff",
        "surface-variant": "#32353d",
        "on-secondary-fixed": "#002113",
        "on-tertiary": "#472a00",
        "inverse-on-surface": "#2d3039",
        "on-error-container": "#ffdad6",
        "on-secondary": "#003824",
        "surface-container-lowest": "#0b0e15",
        "on-tertiary-fixed": "#2a1700",
        "inverse-primary": "#0059c5",
        "surface-dim": "#10131b",
        "surface-container-high": "#272a32",
        "secondary-container": "#00a572",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-container": "#0070f3",
        "outline-variant": "#414754",
        "surface-bright": "#363942",
        "on-surface": "#e0e2ed",
        "on-primary-fixed": "#001a43",
        "primary": "#aec6ff",
        "tertiary": "#ffb95f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "16px",
        "container-max": "1440px",
        "unit": "4px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        "display": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["13px", { "lineHeight": "1.0", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "code-sm": ["12px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
